#!/usr/bin/env python3
"""Compile a pinned MIT iOS app's ORIGINAL translation units without the Apple SDK.

Generated headers are authored ABI *declarations*, NOT UIKit/Foundation/CoreData.
An autogenerated TAPI dylib supplies link metadata ONLY; no imported routine
is actually implemented. This is a load/coverage probe, not a runnable app.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import urllib.request

REPO = "bitrise-io/sample-apps-ios-simple-objc"
COMMIT = "91fef6f5a096220669934793a9256128bc73f25b"
SOURCES = [
    "ios-simple-objc/ios-simple-objc/main.m",
    "ios-simple-objc/ios-simple-objc/AppDelegate.h",
    "ios-simple-objc/ios-simple-objc/AppDelegate.m",
    "ios-simple-objc/ios-simple-objc/ViewController.h",
    "ios-simple-objc/ios-simple-objc/ViewController.m",
]
FOUNDATION = r"""
#ifndef ANYIOS_PROBE_FOUNDATION
#define ANYIOS_PROBE_FOUNDATION
typedef signed char BOOL;
typedef unsigned long NSUInteger;
typedef struct objc_class *Class;
#define YES ((BOOL)1)
#define NO ((BOOL)0)
#define nil ((id)0)
__attribute__((objc_root_class))
@interface NSObject
+ (id)alloc;
- (id)init;
+ (Class)class;
@end
@class NSString, NSURL, NSArray, NSDictionary, NSMutableDictionary, NSError;
@class NSManagedObjectContext, NSManagedObjectModel, NSPersistentStoreCoordinator;
@interface NSString : NSObject @end
@interface NSURL : NSObject
- (NSURL *)URLByAppendingPathComponent:(NSString *)path;
@end
@interface NSArray : NSObject
- (id)lastObject;
@end
@interface NSDictionary : NSObject @end
@interface NSMutableDictionary : NSDictionary
+ (instancetype)dictionary;
- (void)setObject:(id)value forKeyedSubscript:(id)key;
@end
@interface NSError : NSObject
+ (instancetype)errorWithDomain:(NSString *)domain code:(long)code userInfo:(NSDictionary *)info;
- (NSDictionary *)userInfo;
@end
@interface NSFileManager : NSObject
+ (instancetype)defaultManager;
- (NSArray *)URLsForDirectory:(NSUInteger)directory inDomains:(NSUInteger)domain;
@end
@interface NSBundle : NSObject
+ (instancetype)mainBundle;
- (NSURL *)URLForResource:(NSString *)name withExtension:(NSString *)extension;
@end
enum { NSDocumentDirectory = 9, NSUserDomainMask = 1 };
extern NSString *const NSLocalizedDescriptionKey;
extern NSString *const NSLocalizedFailureReasonErrorKey;
extern NSString *const NSUnderlyingErrorKey;
void NSLog(NSString *format, ...);
void abort(void);
NSString *NSStringFromClass(Class cls);
#endif
"""
UIKIT = r"""
#ifndef ANYIOS_PROBE_UIKIT
#define ANYIOS_PROBE_UIKIT
#import <Foundation/Foundation.h>
@protocol UIApplicationDelegate @end
@interface UIResponder : NSObject @end
@interface UIApplication : UIResponder @end
@interface UIWindow : NSObject @end
@interface UIViewController : UIResponder
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
@end
int UIApplicationMain(int argc, char **argv, NSString *principal, NSString *delegate);
#endif
"""
COREDATA = r"""
#ifndef ANYIOS_PROBE_COREDATA
#define ANYIOS_PROBE_COREDATA
#import <Foundation/Foundation.h>
extern NSString *const NSSQLiteStoreType;
@interface NSManagedObjectModel : NSObject
- (instancetype)initWithContentsOfURL:(NSURL *)url;
@end
@interface NSPersistentStoreCoordinator : NSObject
- (instancetype)initWithManagedObjectModel:(NSManagedObjectModel *)model;
- (id)addPersistentStoreWithType:(NSString *)type configuration:(NSString *)config
                            URL:(NSURL *)url options:(NSDictionary *)options error:(NSError **)error;
@end
@interface NSManagedObjectContext : NSObject
- (void)setPersistentStoreCoordinator:(NSPersistentStoreCoordinator *)coordinator;
- (BOOL)hasChanges;
- (BOOL)save:(NSError **)error;
@end
#endif
"""


def download(relative):
    url = "https://raw.githubusercontent.com/" + REPO + "/" + COMMIT + "/" + relative
    with urllib.request.urlopen(url, timeout=20) as result:
        raw = result.read(262145)
    if len(raw) > 262144 or not raw:
        raise ValueError("external upstream file too large or empty")
    return raw


def command(arguments, cwd):
    result = subprocess.run(arguments, cwd=cwd, text=True, capture_output=True, timeout=90)
    if result.returncode:
        raise RuntimeError("build command failed\n" + " ".join(map(str, arguments)) +
                           "\n" + result.stdout + "\n" + result.stderr)
    return result.stdout


def build(clang, linker, nm, outdir):
    outdir.mkdir(parents=True, exist_ok=True)
    report = {
        "source": REPO, "commit": COMMIT, "scope": "original five translation-unit files",
        "framework_headers": "project-authored compile-only declarations",
        "linked_library": "synthetic metadata-only unresolved imports, NO runtime",
        "runnable": False, "status": "unknown", "phase": "fetch",
    }
    try:
        with tempfile.TemporaryDirectory(prefix="anyios-ios-app-") as temp:
            work = Path(temp)
            license_bytes = download("LICENSE")
            if b"The MIT License" not in license_bytes or b"Copyright (c) 2014 Bitrise" not in license_bytes:
                raise ValueError("upstream license was not the expected MIT grant")
            report["license_sha256"] = hashlib.sha256(license_bytes).hexdigest()
            report["license"] = "MIT (actual file checked at pinned revision)"
            folder = work / "sources"
            folder.mkdir()
            for path in SOURCES:
                (folder / Path(path).name).write_bytes(download(path))
            includes = work / "include"
            for subdir, header, body in (
                ("Foundation", "Foundation.h", FOUNDATION),
                ("UIKit", "UIKit.h", UIKIT),
                ("CoreData", "CoreData.h", COREDATA),
            ):
                target = includes / subdir
                target.mkdir(parents=True)
                (target / header).write_text(body, encoding="utf-8")
            report["phase"] = "compile"
            objects = []
            for filename in ("main.m", "AppDelegate.m", "ViewController.m"):
                obj = work / (filename + ".o")
                command([clang, "--target=arm64-apple-ios15.0",
                         "-fobjc-runtime=ios-15.0", "-fno-objc-arc", "-fno-stack-protector",
                         "-Wno-incompatible-pointer-types", "-Wno-objc-root-class",
                         "-Wno-objc-missing-property-synthesis", "-I", str(includes),
                         "-I", str(folder), "-c", str(folder / filename), "-o", str(obj)],
                        work)
                objects.append(obj)
            report["phase"] = "link"
            # Export ONLY the unresolved names from these real upstream object files.
            # This metadata-only TAPI does not claim to implement any framework.
            output = command([nm, "-u"] + [str(p) for p in objects], work)
            symbols = sorted(set(re.findall(r"\b(_[A-Za-z0-9_$\.]+)\s*$", output, re.M)))
            if not symbols:
                raise ValueError("original Objective-C app had no external imports")
            report["metadata_only_imports"] = symbols
            tbd = work / "libAnyiOSProbeUnimplemented.tbd"
            formatted = ", ".join("'" + name.replace("'", "''") + "'" for name in symbols)
            tbd.write_text("--- !tapi-tbd\n"
                           "tbd-version: 4\n"
                           "targets: [ arm64-ios ]\n"
                           "install-name: '/usr/lib/libAnyiOSProbeUnimplemented.dylib'\n"
                           "exports:\n"
                           "  - targets: [ arm64-ios ]\n"
                           "    symbols: [ " + formatted + " ]\n"
                           "...\n", encoding="utf-8")
            executable = outdir / "BitriseSimpleObjC"
            command([linker, "-arch", "arm64", "-platform_version", "ios",
                     "15.0", "15.0", "-seg_page_size", "__TEXT", "0x4000",
                     "-seg_page_size", "__DATA", "0x4000",
                     "-seg_page_size", "__DATA_CONST", "0x4000",
                     "-seg_page_size", "__LINKEDIT", "0x4000",
                     "-execute"] + [str(obj) for obj in objects] +
                    ["-e", "_main", "-L", str(work),
                     "-lAnyiOSProbeUnimplemented", "-o", str(executable)], work)
            report["binary_sha256"] = hashlib.sha256(executable.read_bytes()).hexdigest()
            report["status"] = "linked-with-unimplemented-imports"
            report["phase"] = "inspect"
            print("Linked ORIGINAL Bitrise Objective-C sources with metadata-only placeholder.")
            print("NOT runnable: Objective-C runtime, Foundation, UIKit, Core Data absent.")
    except (OSError, RuntimeError, ValueError) as error:
        report["status"] = "blocked"
        report["error"] = str(error)[-12000:]
        print("Expected compatibility barrier: " + str(error)[-1800:], file=sys.stderr)
    (outdir / "bitrise-build-status.json").write_text(
        json.dumps(report, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    # Always return success when a structured, classified blocker is recorded.
    # CI must separately assert artifact consistency; a successful build is NOT implied.
    return report["status"]


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--clang", default="clang-19")
    parser.add_argument("--linker", default="ld64.lld-19")
    parser.add_argument("--nm", default="llvm-nm-19")
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()
    result = build(args.clang, args.linker, args.nm, args.output_dir)
    print("Bitrise compatibility probe result:", result)
